#!/bin/bash
set -e

. ../common

install_packages \
  rsync \
  htop \
  iotop \
  vim \
  git \
  wget \
  jq \
  pwgen \
  cgmanager \
  polkit \
  python \
  autopep8 \
  go \
  go-tools \

install_aur_packages \
  libcgroup \
  visual-studio-code-bin \
  google-chrome
