#!/bin/bash
set -e

. ../common

install_packages \
  rsync \
  htop \
  iotop \
  dnsutils \
  tcpdump \
  vim \
  git \
  wget \
  bzr \
  jq \
  pwgen \
  keepassxc \
  yubikey-personalization-gui \
  stow \
  shellcheck \
  cgmanager \
  gnome-keyring \
  polkit \
  sshuttle \
  sshfs \
  pandoc \
  python \
  autopep8 \
  go \
  go-tools \
  dep \
  bazel \
  docker \
  firefox \
  libcgroup \
  visual-studio-code-bin \
  google-chrome \
  rambox-bin

# Add user to docker group in order to run it without sudo
usermod -aG docker jotef
systemctl enable docker
