#!/bin/bash
set -e

. ../common

install_packages \
  rsync \
  htop \
  iotop \
  vim \
  git \
  wget \
  jq \
  pwgen \
  stow \
  cgmanager \
  gnome-keyring \
  polkit \
  sshuttle \
  python \
  autopep8 \
  go \
  go-tools \
  bazel

install_aur_packages \
  libcgroup \
  visual-studio-code-bin \
  google-chrome \
  rambox-bin
