#!/bin/bash
set -e

. ../common

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages \
  xorg-server \
  xorg-xrandr \
  xorg-xinit \
  xorg-xset \
  xorg-xsetroot \
  xorg-xprop \
  xsel

install_aur_packages \
  autorandr-git
