#!/bin/bash
set -e

. ../common

# Setup the locales.
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen  
echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen  
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Use zsh, not bash
install_packages zsh zsh-completions

# Add our users
groupadd guests
useradd -m -G adm,ftp,games,http,log,rfkill,sys,systemd-journal,users,uucp,wheel -s /bin/zsh jotef
mkdir /home/jotef
chown -R jotef:jotef /home/jotef
useradd -m -G guests,users -s /bin/zsh guest

# TODO: restrict access to su/sudo commands for non-wheel users

# Set the root password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd jotef
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd jotef
fi

# Setup sudo
install_packages sudo
echo "jotef ALL=(ALL) ALL" >> /etc/sudoers

# Enable ssh
install_packages openssh
systemctl enable sshd

# Fonts
install_aur_packages \
  nerd-fonts-complete \
  ttf-ms-fonts \
  ttf-hack-powerline-git \
  ttf-font-awesome-4

# Timezone
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Time sync
install_packages ntp
systemctl enable ntpd
